name: Gerar meu Aplicativo
on: [push, workflow_dispatch]
jobs:
  construir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java 17 (Para o Motor do Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalando Ferramentas
        run: |
          npm install -g cordova@10.0.0
          cordova platform add android@9.1.0 --no-telemetry || true

      - name: Ajustar Versão do Java para o Build
        run: echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV

      - name: Criar APK
        run: cordova build android --debug --no-telemetry

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: meu-app-sucesso
          path: "*/.apk"
