name: Gerar meu Aplicativo
on: [push, workflow_dispatch]
jobs:
  construir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14' # Versão bem antiga e compatível
      - name: Instalando Tudo
        run: |
          npm install -g cordova@10.0.0
          cordova platform add android@9.1.0 --no-telemetry || true
          cordova build android --debug --no-telemetry
      - name: Download
        uses: actions/upload-artifact@v4
        with:
          name: app-teste
          path: "*/.apk" # Procura o APK em qualquer pasta
